### ISSUE TITLE
Submitting HEIC data

### ISSUE THREAD

**Issue by reaperhulk** [MozillaSecurity/fuzzdata#1]
Thanks for maintaining this corpus of data! I use it with several fuzzers within Google's oss-fuzz infrastructure.

Would this project be willing to accept an HEIC/HEIF file so that I can use it to fuzz ImageMagick's libde265 support more extensively? I'd be happy to put in a PR if you're interested, otherwise I'll find/create another home for it 😄

**Comment by posidron** [comment]
Of course! :-) Please create a PR.

**Comment by reaperhulk** [comment]
Great, I'll send the PR in a bit. Thanks!
